# Generated by Django 3.1.4 on 2021-08-27 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish_list',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField(default=1, unique=True, verbose_name='User Id')),
                ('favorite', models.BooleanField(verbose_name='Favorite')),
                ('cart', models.BooleanField(verbose_name='Cart')),
                ('wished_qty', models.PositiveBigIntegerField(verbose_name='Wished Qty')),
                ('buyied_qty', models.PositiveBigIntegerField(verbose_name='Buyied Qty')),
                ('comic_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='e_commerce.comic', verbose_name='Comic')),
            ],
            options={
                'db_table': 'e_commerce_wish_list',
            },
        ),
    ]
